package com.android.appclock.ui.theme

import androidx.compose.ui.graphics.Color

val ClockBlue = Color(0xFF4856F5)
val ClockBlueDark = Color(0xFF3643D6)
val ClockCyan = Color(0xFF62D9FF)
val ClockMint = Color(0xFF7AE6C2)
val ClockCoral = Color(0xFFFF8B7B)
val ClockWarning = Color(0xFFFFA552)
val ClockSuccess = Color(0xFF2E9B62)
val ClockDanger = Color(0xFFD84D5C)

val LightPrimary = ClockBlue
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE4E7FF)
val LightOnPrimaryContainer = Color(0xFF11174A)
val LightSecondary = Color(0xFF006A83)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFBEEBFF)
val LightOnSecondaryContainer = Color(0xFF001F29)
val LightTertiary = Color(0xFF006D5B)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF84F8DB)
val LightOnTertiaryContainer = Color(0xFF00201A)
val LightBackground = Color(0xFFF6F7FB)
val LightOnBackground = Color(0xFF171B2C)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF171B2C)
val LightSurfaceVariant = Color(0xFFE7EAF4)
val LightOnSurfaceVariant = Color(0xFF44495E)
val LightOutline = Color(0xFF747A91)

val DarkPrimary = Color(0xFFBEC2FF)
val DarkOnPrimary = Color(0xFF16218B)
val DarkPrimaryContainer = Color(0xFF2E3AB8)
val DarkOnPrimaryContainer = Color(0xFFE3E6FF)
val DarkSecondary = Color(0xFF88D2F0)
val DarkOnSecondary = Color(0xFF003544)
val DarkSecondaryContainer = Color(0xFF004D62)
val DarkOnSecondaryContainer = Color(0xFFBEEBFF)
val DarkTertiary = Color(0xFF67DBBF)
val DarkOnTertiary = Color(0xFF00382E)
val DarkTertiaryContainer = Color(0xFF005142)
val DarkOnTertiaryContainer = Color(0xFF84F8DB)
val DarkBackground = Color(0xFF0F1320)
val DarkOnBackground = Color(0xFFE2E6F3)
val DarkSurface = Color(0xFF161B2C)
val DarkOnSurface = Color(0xFFE2E6F3)
val DarkSurfaceVariant = Color(0xFF2B3044)
val DarkOnSurfaceVariant = Color(0xFFC4C8D7)
val DarkOutline = Color(0xFF8D93AA)
